# Generated by Django 4.2.2 on 2023-08-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(default='')),
                ('name', models.CharField(default='', max_length=100)),
                ('accno', models.BigIntegerField(default='')),
                ('ifsc', models.CharField(default='', max_length=100)),
                ('branch_name', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField(default='')),
                ('ename', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('dob', models.DateField(default='')),
                ('econtact', models.BigIntegerField(default='')),
                ('econtact2', models.BigIntegerField(default='')),
                ('qualification', models.CharField(default='', max_length=50)),
                ('doj', models.DateField(default='')),
                ('aadhar', models.BigIntegerField(default='')),
                ('pan', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='', max_length=100)),
                ('blood', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
